config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:show, :new, :create]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :decks do
    resources :games, only: [:new, :create]
  end

  root 'decks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  has_many :guesses
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  has_many :games
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :deck
end

app/models/guess.rb
class Guess < ApplicationRecord
  belongs_to :card
  belongs_to :game
  has_many :guesses
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games
  has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= session[:user_id] && User.find_by_id(session[:user_id]) # Use find_by_id to get nil instead of an error if user doesn't exist
  end

  def logged_in?
    !!current_user
  end

  helper_method :current_user #make this method available in views
  helper_method :logged_in? #make this method available in views

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController

  def index
    @decks = Deck.all
  end

  def new

  end

  def create

  end

  def show
    @user = User.find_by_id(params[:id])
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  def new
    @game = Game.new
  end

  def create
    Game.new(params[:deck_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email]).try(:authenticate, params[:session][:password])
    session[:user_id] = @user.id
    redirect_to @user
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    @user.save
    redirect_to @user
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/decks/index.html.erb
<h1>Decks</h1>

<ul>
  <% @decks.each do |deck| %>
    <li><%= link_to deck.name, new_deck_game_path(deck) %></li>
  <% end %>
</ul>

app/views/decks/show.html.erb
Show page for <%= @user.username %>

app/views/games/new.html.erb
<%= form_for @game do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :username %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebFlashcards</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <p>Hello <%= current_user.username %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <div>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
hello <%= @user.username %>